export const cardImage = {
    "Fool": require("../assets/arcanas/Fool.webp"),
    "Magician": require("../assets/arcanas/Magician.webp"),
    "Priestess": require("../assets/arcanas/Priestess.webp"),
    "Empress": require("../assets/arcanas/Empress.webp"),
    "Emperor": require("../assets/arcanas/Emperor.webp"),
    "Hierophant": require("../assets/arcanas/Hierophant.webp"),
    "Lovers": require("../assets/arcanas/Lovers.webp"),
    "Chariot": require("../assets/arcanas/Chariot.webp"),
    "Strength": require("../assets/arcanas/Strength.webp"),
    "Hermit": require("../assets/arcanas/Hermit.webp"),
    "Fortune": require("../assets/arcanas/Fortune.webp"),
    "Justice": require("../assets/arcanas/Justice.webp"),
    "Hanged": require("../assets/arcanas/Hanged Man.webp"),
    "Death": require("../assets/arcanas/Death.webp"),
    "Temperance": require("../assets/arcanas/Temperance.webp"),
    "Devil": require("../assets/arcanas/Devil.webp"),
    "Tower": require("../assets/arcanas/Tower.webp"),
    "Star": require("../assets/arcanas/Star.webp"),
    "Moon": require("../assets/arcanas/Moon.webp"),
    "Sun": require("../assets/arcanas/Sun.webp"),
    "Judgement": require("../assets/arcanas/Judgement.webp"),
    "Faith": require("../assets/arcanas/Faith.webp"),
    "Faith broken": require("../assets/arcanas/Faith-broken.webp"),
    "Councillor": require("../assets/arcanas/Councillor.webp"),
    "CardBack": require("../assets/arcanas/back.webp"),
}